sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
services:
  - docker
env:
  global:
    - JWT_VERSION=1.0.0
    - PROJECT_DAEMON_VERSION=0.4.0
    - PROJECT_VERSION=0.4.0
    - STATIC_VERSION=0.4.0
addons:
  hosts:
    - local.montage.studio

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version
  - git submodule init
  - git submodule update
  # NodeJS Install
  - npm install
  # Update public certs
  - sudo update-ca-certificates --verbose
  # Build images
  - docker-compose -f traefik-stack.yml pull
  - docker-compose -f firefly-stack.yml build
  - docker-compose -f project-daemon/user-stacks/basic-stack.yml build

before_script:
  - export DOCKER_CLIENT_TIMEOUT=120
  - npm run generate-local-certificate
  - docker swarm init
script:
  - npm start
  - npm run lint
  - runSlowSpecs=true npm test
  - sleep 120
  - docker ps
  - docker ps | grep -q traefik_traefik
  - docker ps | grep -q firefly_auth
  - docker ps | grep -q firefly_jwt
  - docker ps | grep -q firefly_static
  - docker ps | grep -q firefly_project-daemon
after_script:
  - npm stop
  - docker swarm leave --force

deploy:
  - provider: script
    script: docker-compose -f firefly-stack.yml push && docker-compose -f project-daemon/user-stacks/basic-stack.yml push
