sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - >
    curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - >
    sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes --allow-unauthenticated install docker-engine
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version
  # NodeJS Install
  - "npm install"
  # Update public certs
  - sudo update-ca-certificates --verbose
addons:
  hosts:
    - local-aurora.montagestudio.com
before_script:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
  - export DOCKER_CLIENT_TIMEOUT=120
  - sh docker-swarm-start.sh
script:
  - npm run lint
  - sleep 25
  - docker ps | grep -q load-balancer
  - docker ps | grep -q login
  - docker ps | grep -q static
  - docker ps | grep -q project-daemon
  - npm run test:all
after_script:
  - sh docker-swarm-stop.sh
