sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
services:
  - docker
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version
  # NodeJS Install
  - "npm install"
  # Update public certs
  - sudo update-ca-certificates --verbose
addons:
  hosts:
    - local.montage.studio
before_script:
  - export DOCKER_CLIENT_TIMEOUT=120
  - docker swarm init
  - npm start
script:
  - npm run lint
  - sleep 25
  - docker ps | grep -q load-balancer
  - docker ps | grep -q login
  - docker ps | grep -q static
  - docker ps | grep -q project-daemon
  - runSlowSpecs=true npm test
after_script:
  - npm stop
  - docker swarm leave --force
