version: "3.1"

services:
  load-balancer:
    build:
      context: ./deploy-docker/services/load-balancer/
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - static
      - login
      - project
  static:
    build:
      context: ./deploy-docker/services/static/
    networks:
      backend:
      outside:
        ipv4_address: 162.243.35.210
    ports:
      - "8183:80"
    volumes:
      - firefly-src:/srv/filament/
  login:
    build:
      context: ./deploy-docker/services/login/
    networks:
      backend:
      outside:
        ipv4_address: 107.170.4.128
    ports:
      - "8184:2440"
      - "8104:8104"
    depends_on:
      - static
    volumes:
      - ./:/srv/firefly/
  project:
    build:
      context: ./deploy-docker/services/project/
    networks:
      backend:
      outside:
        ipv4_address: 10.5.0.6
    ports:
      - "8185:2440"
      - "8105:8105"
    depends_on:
      - static
    volumes:
      - ./:/srv/firefly/

networks:
    frontend:
    backend:
    outside:
      driver: overlay
      ipam:
        config:
        - subnet: 162.243.35.0/24
        - subnet: 107.170.4.0/24
        - subnet: 10.5.0.0/24

volumes:
  firefly-src: 
  filament-src: