version: "3.2"

services:
  load-balancer:
    image: 127.0.0.1:5000/load-balancer
    build:
      context: ./load-balancer/
    networks:
      - frontend
      - backend
    ports:
      # TODO Choose port conditionally based on env
      # We should use 2440 for dev and 80 for staging/prod
      - "2440:80"
      #- "80:80"
      #- "443:443"
    depends_on:
      - static
      - login
      - project-daemon
    environment:
      - NODE_ENV=$NODE_ENV
  static:
    image: nginx
    networks:
      - backend
    ports:
      - "8183:80"
    volumes:
      - /firefly/static/nginx.conf:/etc/nginx/nginx.conf:ro
      - /filament/:/srv/app/
      - /firefly/inject/adaptor/:/srv/app/adaptor/
  login:
    image: 127.0.0.1:5000/login
    build:
      context: ./login/
    networks:
      - backend
    ports:
      - "8184:2440"
      - "8104:8104"
    depends_on:
      - static
    volumes:
      - /firefly/:/srv/firefly/
      - /filament/:/srv/filament/
  project-daemon:
    image: 127.0.0.1:5000/project-daemon
    build:
      context: ./project-daemon/
    networks:
      - backend
    ports:
      - "8185:2440"
      - "8105:8105"
    depends_on:
      - static
    volumes:
      - /firefly/:/srv/firefly/
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
    frontend:
    backend:
      attachable: true
