version: "3.1"

services:
  load-balancer:
    image: 127.0.0.1:5000/load-balancer
    build:
      context: ./deploy-docker/services/load-balancer/
    networks:
      - frontend
      - backend
    ports:
      # TODO Choose port conditionally based on env
      # We should use 2440 for dev and 80 for staging/prod
      - "2440:80"
      #- "80:80"
      #- "443:443"
    depends_on:
      - static
      - login
      - project
    environment:
      - NODE_ENV=$NODE_ENV
  static:
    image: 127.0.0.1:5000/static
    build:
      context: ./deploy-docker/services/static/
    networks:
      backend:
      outside:
        ipv4_address: 162.243.35.210
    ports:
      - "8183:80"
    volumes:
      - firefly-src:/srv/filament/
  login:
    image: 127.0.0.1:5000/login
    build:
      context: ./deploy-docker/services/login/
    networks:
      backend:
      outside:
        ipv4_address: 107.170.4.128
    ports:
      - "8184:2440"
      - "8104:8104"
    depends_on:
      - static
    volumes:
      - ./:/srv/firefly/
  project:
    image: 127.0.0.1:5000/project
    build:
      context: ./deploy-docker/services/project/
    networks:
      backend:
      outside:
        ipv4_address: 162.243.121.4
    ports:
      - "8185:2440"
      - "8105:8105"
    depends_on:
      - static
    volumes:
      - ./:/srv/firefly/

networks:
    frontend:
    backend:
    outside:
      driver: overlay
      ipam:
        config:
        - subnet: 162.243.35.0/24
        - subnet: 107.170.4.0/24
        - subnet: 162.243.121.4/24

volumes:
  firefly-src: 
  filament-src: