version: "3.3"

services:
  traefik:
    ports:
      - "2440:443"
    volumes:
      - ./traefik/ssl/cert.pem:/etc/ssl/cert.pem:ro
      - ./traefik/ssl/serverkey.pem:/etc/ssl/serverkey.pem:ro
  static:
    volumes:
      - ./static/filament/:/srv/app/
      - ./static/nginx.conf:/etc/nginx/nginx.conf
  project-daemon:
    volumes:
      - ./project-daemon/:/srv/project-daemon/
      - /srv/project-daemon/node_modules/
  