version: "3.3"

services:
  traefik:
    image: traefik:latest
    command: --docker.domain=${FIREFLY_HOSTNAME}
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
      - "2442:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /acme.json:/acme.json
    configs:
      - source: traefik-config
        target: /traefik.toml
    deploy:
      placement:
        constraints:
          - node.role == manager
  auth:
    image: montagestudio/montage-auth:develop-SNAPSHOT
    networks:
      - backend
    environment:
      - GITHUB_ID
      - GITHUB_SECRET
      - GITHUB_SCOPES='user,public_repo,repo,gist'
      - APP_SSL='false'
      - APP_URL=${FIREFLY_APP_URL}
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.docker.network=traefik_net"
        - "traefik.frontend.rule=PathPrefix:/auth"
        - "traefik.frontend.priority=2"
  jwt:
    image: registry.montage.studio/firefly/jwt:${JWT_VERSION:-latest}
    build: ./jwt
    networks:
      - backend
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=traefik_net"
        - "traefik.frontend.rule=Host:jwt.${FIREFLY_HOSTNAME}"
  static:
    image: registry.montage.studio/firefly/static:${STATIC_VERSION:-latest}
    build: ./static
    networks:
      - backend
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=traefik_net"
        - "traefik.frontend.rule=Host:${FIREFLY_HOSTNAME}"
        - "traefik.frontend.priority=1"
  project-daemon:
    image: registry.montage.studio/firefly/project-daemon:${PROJECT_DAEMON_VERSION:-latest}
    build: ./project-daemon
    networks:
      - backend
      - projects
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV
      - PROJECT_ROOT
      - FIREFLY_PORT
      - FIREFLY_APP_URL
      - FIREFLY_PROJECT_URL
      - PROJECT_VERSION
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=2440"
        - "traefik.docker.network=traefik_net"
        - "traefik.frontend.rule=Host:project.${FIREFLY_HOSTNAME},api.${FIREFLY_HOSTNAME},build.${FIREFLY_HOSTNAME},ws.${FIREFLY_HOSTNAME}"
networks:
  frontend:
  backend:
    driver: overlay
  projects:
    driver: overlay
    attachable: true

configs:
  traefik-config:
    file: traefik/traefik.toml
