version: "3.3"

services:
  traefik:
    image: traefik
    command: --docker.domain=${FIREFLY_HOSTNAME}
    networks:
      - net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: traefik-config
        target: /traefik.toml
    deploy:
      placement:
        constraints:
          - node.role == manager
  static:
    image: 127.0.0.1:5000/static
    networks:
      - net
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=firefly_net"
        - "traefik.frontend.rule=Host:${FIREFLY_HOSTNAME}"
  login:
    image: 127.0.0.1:5000/login
    networks:
      - net
    environment:
      - NODE_ENV
      - FIREFLY_PORT
      - FIREFLY_APP_URL
      - FIREFLY_PROJECT_URL
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=2440"
        - "traefik.docker.network=firefly_net"
        - "traefik.frontend.rule=Host:auth.${FIREFLY_HOSTNAME}"
  project-daemon:
    image: 127.0.0.1:5000/project-daemon
    networks:
      - net
    depends_on:
      - static
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV
      - USE_SRC_DOCKER_VOLUMES
      - SWARM_SINGLE_NODE
      - FIREFLY_PORT
      - FIREFLY_APP_URL
      - FIREFLY_PROJECT_URL
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=2440"
        - "traefik.docker.network=firefly_net"
        - "traefik.frontend.rule=Host:project.${FIREFLY_HOSTNAME},api.${FIREFLY_HOSTNAME},build.${FIREFLY_HOSTNAME},ws.${FIREFLY_HOSTNAME}"

networks:
  net:
    driver: overlay
    attachable: true

configs:
  traefik-config:
    file: traefik.toml