version: "3.3"

services:
  traefik:
    image: traefik
    command: --docker.domain=${FIREFLY_HOSTNAME}
    networks:
      - net
    ports:
      - "2440:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssl/cert.pem:/etc/ssl/cert.pem:ro
      - ./ssl/serverkey.pem:/etc/ssl/serverkey.pem:ro
    configs:
      - source: traefik-config
        target: /traefik.toml
    deploy:
      placement:
        constraints:
          - node.role == manager
  static:
    image: 127.0.0.1:5000/static
    networks:
      - net
    volumes:
      - ./static/filament/:/srv/app/
      - /srv/app/node_modules/
      - ./common/inject/adaptor/:/srv/app/adaptor/
    configs:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=firefly_net"
        - "traefik.frontend.rule=Host:${FIREFLY_HOSTNAME}"
  login:
    image: 127.0.0.1:5000/login
    networks:
      - net
    volumes:
      - ./login/:/srv/login/
      - /srv/login/node_modules/
      - ./common/:/srv/login/common/
      - /srv/login/common/node_modules/
    environment:
      - NODE_ENV
      - FIREFLY_PORT
      - FIREFLY_APP_URL
      - FIREFLY_PROJECT_URL
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=2440"
        - "traefik.docker.network=firefly_net"
        - "traefik.frontend.rule=Host:auth.${FIREFLY_HOSTNAME}"
  project-daemon:
    image: 127.0.0.1:5000/project-daemon
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./project-daemon/:/srv/project-daemon/
      - /srv/project-daemon/node_modules/
      - ./common/:/srv/project-daemon/common/
      - /srv/project-daemon/common/node_modules/
    environment:
      - NODE_ENV
      - WORKING_DIR
      - USE_SRC_DOCKER_VOLUMES
      - SWARM_SINGLE_NODE
      - FIREFLY_PORT
      - FIREFLY_APP_URL
      - FIREFLY_PROJECT_URL
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.port=2440"
        - "traefik.docker.network=firefly_net"
        - "traefik.frontend.rule=Host:project.${FIREFLY_HOSTNAME},api.${FIREFLY_HOSTNAME},build.${FIREFLY_HOSTNAME},ws.${FIREFLY_HOSTNAME}"

networks:
  net:
    driver: overlay
    attachable: true

configs:
  traefik-config:
    file: traefik.toml
  nginx-config:
    file: static/nginx.conf
