version: "3.3"

services:
  traefik:
    image: traefik:latest
    command: --docker.domain=${FIREFLY_HOSTNAME}
    networks:
      - net
    ports:
      - "80:80"
      - "443:443"
      - "2442:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /acme.json:/acme.json
    configs:
      - source: traefik-config
        target: /traefik.toml
    deploy:
      placement:
        constraints:
          - node.role == manager
  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - 2441:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  net:
    driver: overlay

configs:
  traefik-config:
    file: traefik.toml