version: "3.3"

services:
  traefik:
    ports:
      - "2440:443"
      - "80" # Put to override the "443:443" definition in traefik-stack.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssl/cert.pem:/etc/ssl/cert.pem:ro
      - ./ssl/serverkey.pem:/etc/ssl/serverkey.pem:ro
