---
- name: ensure droplet exists
  digital_ocean: >
    api_key={{ api_key }}
    client_id={{ client_id }}
    state=present
    command=droplet
    name={{ droplet_name }}
    size_id={{ default_size }}
    region_id={{ default_region }}
    image_id={{ default_image }}
    wait_timeout=500
    unique_name=true
    private_networking=true
  register: droplet
  with_items: droplets

- add_host: >
    name=deploy-server
    ansible_ssh_host={{ item.droplet.ip_address }}
  with_items: droplet.results

- debug: msg="IP is {{ item.droplet.ip_address }}"
  with_items: droplet.results
