---
- name: Ensure deploy user exists
  user: >
    name=deploy
    home=/home/deploy
    createhome=yes
- name: Ensure ruby is installed
  apt: >
    name=ruby
- name: Ensure tugboat is configured
  template: >
    src=/templates/deploy_server/tugboat.tpl
    dest=/home/deploy/.tugboat
