-   name:   Ensure git is installed and up to date
    apt:
        name:           git
        state:          latest
        update_cache:   yes
-   name:   Ensure build-essential is installed and up to date
    apt:
        name:   build-essential
        state:  latest
-   name:   Ensure ruby-dev is installed and up to date
    apt:
        name:   ruby-dev
        state:  latest
-   name:   Ensure unzip is installed and up to date
    apt:
        name:   unzip
        state:  latest
-   name:   Ensure bsdtar is installed and up to date
    apt:
        name:   bsdtar
        state:  latest
-   name:   Ensure .ssh directory exists
    file:
        dest:   /root/.ssh
        state:  directory
        mode:   0700
# -   name:   Ensure deploy key is available
#     copy:
#         src:    deploy.pem
#         dest:   /root/.ssh/deploy.pem
#         mode:   0400
# -   name:   Ensure .ssh/config is available
#     copy:
#         src:    config.ssh
#         dest:   /root/.ssh/config
#         mode:   0400
-   name:   Ensure known_hosts is available
    copy:
        src:    known_hosts
        dest:   /root/.ssh/known_hosts
        mode:   0400
-   name:   Ensure tugboat config is available
    copy:
        src:    tugboat
        dest:   /root/.tugboat
        mode:   0400
