version: "3.3"

services:
  project:
    image: registry.montage.studio/firefly/project:0.2.0
  build:
    context: .
    dockerfile: project/Dockerfile
  env:
    - NODE_ENV
  deploy:
    placement:
      constraints: [node.role == worker]
    replicas: 1
