module.exports = {
    VERSION_INVALID: 0,
    DEPENDENCY_MISSING: 1,
    DEPENDENCY_EXTRANEOUS: 2,
    PACKAGE_FILE_INVALID: 3,
    DEPENDENCY_NAME_NOT_VALID: 4000,
    PROJECT_PATH_NOT_VALID: 4001,
    FS_PERMISSION: 4002,
    DEPENDENCY_NOT_FOUND: 4003
};
